### ISSUE TITLE
Web speech api on ios device mic not stopping

### ISSUE THREAD

**Issue by JaydonChion** [mdn/dom-examples#118]
Hi, I am trying to use the web speech api on ios's safari. The issue is after the user done speaking and the api has successfully recognize the speech, the mic doesn't stop listening. I saw someone facing similar issue here https://developer.apple.com/forums/thread/699881 
Any idea what is happening and how to solve it?

Thank you.

*p.s it is working fine on android's chrome

**Comment by Rumyra** [comment]
Hi @JaydonChion there seems to be some answers to your issue in the thread here https://stackoverflow.com/questions/75498609/safari-webkitspeechrecognition-continuous-bug - hope that helps
