### ISSUE TITLE
Restore commit log from mdn/web-speech-api and mdn/webgl-examples

### ISSUE THREAD

**Issue by clemens-tolboom** [mdn/dom-examples#134]
It seems (never tried) possible to keep the commits according anwers in https://stackoverflow.com/questions/17371150/moving-git-repository-content-to-another-repository-preserving-history

It only required to prepare https://github.com/mdn/web-speech-api moving the tree into a subdirectory `/web-speech-api` beforehand.

Hope you can redo this.
@schalkneethling according to https://github.com/mdn/dom-examples/commits/master/web-speech-api

**Comment by teoli2003** [comment]
cc/ @Rumyra, too.

**Comment by MrBrain295** [comment]
This was also done to [this repository](https://github.com/mdn/webgl-examples).

**Comment by teoli2003** [comment]
@schalkneethling Do you plan to fix this? This repo is low-activity, so it is still possible to revert/redo this, but the more we wait, the more merges will be needed.

**Comment by schalkneethling** [comment]
> @schalkneethling Do you plan to fix this? This repo is low-activity, so it is still possible to revert/redo this, but the more we wait, the more merges will be needed.

Yup, now that I know the process and have documented it, I will definitely redo this one.

**Comment by teoli2003** [comment]
(I think there are at least two of them, web-speech-api and webgl-examples)

**Comment by Rumyra** [comment]
Open issue in team project board for ref https://github.com/mdn/mdn/issues/155

**Comment by schalkneethling** [comment]
Hey folks, as Ruth mentioned above. I am in the process of redoing some of the repositories and all future moves will retain all commit history. I also realized that we want to merge style these pull requests and not squash merge.

Squash merge will squash everything into a single commit, whereas a "merge merge"? :) will add each commit individually into history.

**Comment by clemens-tolboom** [comment]
I'm not sure I get this closing ... I do not see restoration of the commits in https://github.com/mdn/dom-examples/commits/main/web-speech-api

So is this done or planned to get done? Or did I missed something?
