### ISSUE TITLE
MediaRecorder example not working on Download Audio

### ISSUE THREAD

**Issue by neviaumi** [mdn/dom-examples#147]
https://github.com/mdn/dom-examples/tree/master/media/web-dictaphone

Example here was not working when click download recorded audio.

My Browser : Chrome 103
OS: Mac OS 12.3.1

I guess the root cause is 
https://github.com/mdn/dom-examples/blob/master/media/web-dictaphone/scripts/app.js#L80

it specific type to `ogg` but in fact it was webm format .

for prove that, i have download the file and rename the extension to webm from ogg manually . It would working perfectly

**Comment by zfox23** [comment]
Hi @neviaumi :) Thank you for your patience here. I have a few questions about this issue:

1. When you say you "clicked download recorded audio," which button are you referring to? Are you referring to right-clicking the native browser audio player and downloading from there? Or is there another button that I'm missing?
    ![image](https://github.com/mdn/dom-examples/assets/3409031/e6e27eca-87f3-4893-8524-8bb1c1a9386e)
2. After you download the audio, what are you using to play it back? On my Mac, when I download the audio, I can play it back without changing the file extension using VLC.

**Comment by neviaumi** [comment]
Hey @zfox23 , yes, that what i referring to !

And i think the problem was resolved by browser update already. 

will close the issue now.
