### ISSUE TITLE
Notification not working on Windows 10 Action Center

### ISSUE THREAD

**Issue by DiegoGorgazzi** [mdn/dom-examples#173]
In Windows 10, when the notification closes, it is pushed to Windows 10's action center. Clicking on the notification action center (after the notification at the bottom has closed) directs to the root URL, not the URL that dispatched the notification. 

For example, the URL that dispatched the notification might be https://mdn.github.io/to-do-notifications/ . However, clicking on the notification that made it into the Action Center will direct to https://mdn.github.io (along with an error message).

![image](https://user-images.githubusercontent.com/44508750/83100691-5b2c6a80-a065-11ea-91c2-a5ca0c480520.png)

**Comment by schalkneethling** [comment]
You can find the code here https://github.com/mdn/dom-examples/tree/main/to-do-notifications

**Comment by Rumyra** [comment]
Due to the age of this issue I am closing - feel free to reopen @DiegoGorgazzi if it's still an issue
