### ISSUE TITLE
webkitSpeechRecognition not working for other languages in iPhone

### ISSUE THREAD

**Issue by Sendhilkumaar** [mdn/dom-examples#197]
am trying to use the webkitSpeechRecognition to get the spoken word by the user. It works in desktop for English and Tamil (lang='ta'). On iPhone it works for English but not for Tamil (lang = 'ta').

In the following code, 
if lang='en-us', the page asks for access to microphone,
if lang = 'ta', the page doesn't work (no request to access microphone)

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content=
		"width=device-width, initial-scale=1.0">

	<title>Speech to Text</title>
</head>

<body>
	<div class="words" contenteditable>
		<p id="p"></p>
	</div>

	<script>
		var speech = true;
		window.SpeechRecognition = window.SpeechRecognition
						|| window.webkitSpeechRecognition;
	
		const recognition = new SpeechRecognition();
		**recognition.lang = 'ta';**

		recognition.interimResults = true;
		const words = document.querySelector('.words');
		words.appendChild(p);
		console.log(words)

		recognition.addEventListener('result', e => {
			const transcript = Array.from(e.results)
				.map(result => result[0])
				.map(result => result.transcript)
				.join('')

			document.getElementById("p").innerHTML = transcript;
			console.log(transcript);
		});
		
		if (speech == true) {
			recognition.start();
			recognition.addEventListener('end', recognition.start);
		}
	</script>
</body>

</html>

**Comment by sinchang** [comment]
Hi @Sendhilkumaar, looks like `ta` is an invalid lang, have you tried `ta-IN` or `ta-LK`?

You can check here https://gist.github.com/typpo/b2b828a35e683b9bf8db91b5404f1bd1 for more lang.

**Comment by Sendhilkumaar** [comment]
hi @sinchang , it doesn't work with ta-IN, ta-LK as well. It does work well for "en".
