### ISSUE TITLE
dom-examples-main/webgl-examples/tutorial/tetrahedron not working

### ISSUE THREAD

**Issue by TJP623** [mdn/dom-examples#201]
tetrahedron says gl-matrix.js and webgl.css don't exist.

**Comment by teoli2003** [comment]
How did you run the tetrahedron? Inside MDN, inside GitHub, or locally?

**Comment by caugner** [comment]
@TJP623 If you still experience the problem, can you answer the question in the previous comment? 🙏

**Comment by zfox23** [comment]
Hi @TJP623 :) Please let us know if you're still experiencing this issue. Otherwise, I'll close it tomorrow evening. Thank you!

**Comment by Adderin** [comment]
**Yes this issue still persists**
Way of fixing - in index.html
1) Path to _webgl.css_ should be changed or created locally, for instance [see example here](https://github.com/mdn/webvr-tests/blob/bb5c886e2c877211562bb360630d15ab56336155/webvr/raw-webgl-example/webgl.css)
2)  `<script src="../gl-matrix.js"></script>` should be changed to 
` <script src="https://cdnjs.cloudflare.com/ajax/libs/gl-matrix/2.8.1/gl-matrix-min.js"></script>` or any other gl-matrix.js link

**Comment by zfox23** [comment]
I see what you are saying @Adderin, thank you.

[Our GitHub-hosted Tetrahedron tutorial located here](https://mdn.github.io/dom-examples/webgl-examples/tutorial/tetrahedron/) reports 404s for `webgl.css` and `gl-matrix.js`. I can't find what `webgl.css` file it's supposed to be referencing (there isn't one in the repository, and I can't find an associated MDN tutorial). Same story with `gl-matrix.js` - it doesn't exist anywhere in the `dom-examples` repository.

Fixing the problem with `gl-matrix.js` would be straightforward, but I don't know what `webgl.css` file it's supposed to be referencing.

Any ideas, @caugner?
