### ISSUE TITLE
boundary event is not fired for any lang other than "en-US-Microsoft"

### ISSUE THREAD

**Issue by sunnykoundal** [mdn/dom-examples#218]
When I change language from default to en-US-Google US English or en-GB-Google UK English Female, it does not call the event onboundary.

**Comment by caugner** [comment]
It looks like there is no example mentioning "boundary" in this repository.

@sunnykoundal Can you please provide more details, like which example your issue refers to, and steps to reproduce it? 🙏

**Comment by caugner** [comment]
Thanks again for raising this issue.

As we haven't heard back from you, we will go ahead and close this issue. If you think it's still relevant, please reply to the previous comment and reopen the issue. 🙏 

We appreciate your understanding.
