### ISSUE TITLE
typo in comments

### ISSUE THREAD

**Issue by jessepeterman** [mdn/dom-examples#22]
near the end of the html: "bebugging"

**Comment by chrisdavidmills** [comment]
Hi there! Which file does this typo appear in?

**Comment by jessepeterman** [comment]
sorry about that, didn’t realize it didn’t connect the file I was on: 

touchevents, line 197 

 <!-- UI for logging/bebugging —>

Jesse

**Comment by chrisdavidmills** [comment]
No worries. I've fixed the typo. Thanks for reporting it.
