### ISSUE TITLE
Poor Color Contrast of "run shared worker" Example Page

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/dom-examples#222]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker

### What specific section or headline is this issue about?

Examplpe

### What information was incorrect, unhelpful, or incomplete?

After I clicked the "run shared worker" link ( https://mdn.github.io/dom-examples/web-workers/simple-shared-worker/ ), I noticed the color contrast of the page made it difficult to read the text. The second page (  https://mdn.github.io/dom-examples/web-workers/simple-shared-worker/index2.html ) has the same color contrast issue.

When I tabbed to the first problem, the background for the FORM now had enough color contrast, but as I tabbed to the first INPUT field, the color contrast went back to very difficult to read.

If you need more, I can check the items for color contrast, but I assume someone else can do that using a color contrast tool, depending on the overall look the page is going for.

Please see the attached screenshot to show the poor color contrast.

### What did you expect to see?

I was expecting to be able to read the text to start with, but at least when a person tabbed to the FORM, the white background would stay there no matter if they were focusing on the background or an INPTU field.

### Do you have any supporting links, references, or citations?

No.

### Do you have anything more you want to share?

No.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/sharedworker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/sharedworker/index.md
* Last commit: https://github.com/mdn/content/commit/4ba12fec878a1f941492ada3edd467bfd76532cf
* Document last modified: 2023-03-03T11:36:23.000Z

</details>

**Comment by bsmth** [comment]
Hi @jfc3-dol - I've moved the issue over to the dom-examples repository which is where the source for this lives.

**Comment by jfc3-dol** [comment]
@bsmth 

Thanks for the heads up. Hope the fix is going well.
