### ISSUE TITLE
Error on Safari

### ISSUE THREAD

**Issue by dmb0058** [mdn/dom-examples#233]
Running the web-dictaphone on Safari Version 16.2 (18614.3.7.1.5) under macOS Ventura 13.1 (22C65) appears to work but the media player displays an error - see screenshot.

I don't think this is a local configuration issue?
![Screenshot 2023-10-22 at 11 29 47](https://github.com/mdn/dom-examples/assets/4682049/4ef50c50-fc40-4c46-a1b6-e64cd1628cb5)

**Comment by kathekon** [comment]
having the exact same issue!

**Comment by cheburashka5** [comment]
Same issue. Is there a fix or another example of successfully recording and playing back audio on Safari?

**Comment by mavavilj** [comment]
Please fix the demo for Safari.

**Comment by teoli2003** [comment]
A link to the demo would help.

**Comment by mavavilj** [comment]
https://mdn.github.io/dom-examples/media/web-dictaphone/
