### ISSUE TITLE
Channel Messaging Examples are confusing at best.

### ISSUE THREAD

**Issue by Kaiido** [mdn/dom-examples#25]
I fail to see the point of [channel-messaging-multimessage](https://github.com/mdn/dom-examples/tree/master/channel-messaging-multimessage) example...

Why is a new `MessageChannel` created every time, instead of simply passing the new messages in the MessagePort?  
That makes the use of `WindowObject.postMessage` and `MessagePort.postMessage` really unclear: it sounds like either we can postMessage to only a single port, or that MessageChannel is a *single-shot* API, this later speculation being comforted by weird wording in MDN's [Using channel messaging](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging#Use) article:

> Message channels on the other hand can provide a secure channel that **a single data item** can be sent down, from one browsing context to another, **after which the channel is closed**. 
<!--><sup>[emphasize mines]</sup>

That surely can be heard as channel messaging **is** "single-shot", and it actually have been at least by the asker of [this question on stackoverflow](https://stackoverflow.com/questions/51201120/using-messagechannel-bidirectionally-for-multiple-messages-between-page-and-if/).

So except if it is really a "single-shot" API and that **I** got it all wrong, (in this case all implementations would have got it wrong too)  I think *multimessage* is actually a *basic usage*, that it should be rewritten to show a basic usage (i.e reusing the MessagePorts), and that what is currently called *"basic"* should be renamed *single-message*.

**Comment by chrisdavidmills** [comment]
Hrm, I think you have got a good point here. This is rather confusing. Would you be willing to help us update the examples and the text? I'd be happy to review a pull request to improve these demos.

**Comment by ollelauribostrom** [comment]
@chrisdavidmills @Kaiido 

I've made some updates to the docs which hopefully makes things less confusing (and that uses the updated example provided in my PR). What do you think? Would love some feedback on improvements etc. 

Updated pages:
- https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging
- https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel
- https://developer.mozilla.org/en-US/docs/Web/API/MessagePort

**Comment by chrisdavidmills** [comment]
Looks good; I've given the pages a copy edit.
