### ISSUE TITLE
Code examples have stray <script> tags

### ISSUE THREAD

**Issue by 3limin4t0r** [mdn/dom-examples#267]
### What information was incorrect, unhelpful, or incomplete?

A lot code examples in the `mdn/dom-examples` codebase with inline JavaScript have their `<script>` tag placed after the `</body>` close tag. Though the JavaScript is executed, this is technically invalid. The [HTML5 specification][] tells us that the body can only contain a `<head>` and `<body>` tags.

> ### 4.1.1 The `html` element [§][HTML5 specification]
> 
>   - **[Categories][]:**
>     None.
>   - **[Contexts in which this element can be used][]:**
>     As document's [document element][].
>     Wherever a subdocument fragment is allowed in a compound document.
>   - **[Content model][]:**
>     A [`head`][] element followed by a [`body`][] element.

When looking at the source of a page via `view-source:https://mdn.github.io/dom-examples/abort-api/` Firefox will also notify the reader that the tag isn't placed correctly.

![screenshot view-source Firefox][]

Validators like https://validator.w3.org will also yield the same error when validating the page: 

> Error: Stray start tag `script`.

Examples of misplacement of the `<script>` can be found plentiful within the `mdn/dom-examples` codebase. Here are some examples:

https://github.com/mdn/dom-examples/blob/929e39675d42b6642e96ede0b7cf4aa25eb822f5/abort-api/index.html#L39-L40
https://github.com/mdn/dom-examples/blob/929e39675d42b6642e96ede0b7cf4aa25eb822f5/fetch/basic-fetch/index.html#L17-L18
https://github.com/mdn/dom-examples/blob/929e39675d42b6642e96ede0b7cf4aa25eb822f5/fetch/fetch-response/index.html#L16-L17

[HTML5 specification]: https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
[Categories]: https://html.spec.whatwg.org/multipage/dom.html#concept-element-categories
[Contexts in which this element can be used]: https://html.spec.whatwg.org/multipage/dom.html#concept-element-contexts
[document element]: https://dom.spec.whatwg.org/#document-element
[Content model]: https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model
[`head`]: https://html.spec.whatwg.org/multipage/semantics.html#the-head-element
[`body`]: https://html.spec.whatwg.org/multipage/sections.html#the-body-element
[screenshot view-source Firefox]: https://github.com/mdn/dom-examples/assets/1522964/dbf34064-836d-47ea-974b-6ecdd4f215d9

### What did you expect to see?

I would expect to see valid HTML, meaning that the `<script>` tags have to be placed before the closing `</body>` tag (or inside the `<head>`).

**Comment by bsmth** [comment]
Thanks a lot for opening this one. There's a linked PR above that addresses these violations, although there are a few more to fix in this repo afterwards.
