### ISSUE TITLE
Add `alt` attribute to image inside `<figure>` element to improve accessibility

### ISSUE THREAD

**Issue by manav-sharma69** [mdn/dom-examples#275]
### What information was incorrect, unhelpful, or incomplete?

Link to live example: [Basic View Transitions API demo](https://mdn.github.io/dom-examples/view-transitions/spa/)
<br>
Improve **incomplete** code:
- The image in `<figure>` element do not have an `alt` attribute. 
- According to W3's documentation, we should add the `alt` attribute whenever possible. 
- In this example's case, all images have a `name` in `imageData` array. So, we do have `alt` but haven't added them in the image in `<figure>` element. 
- The image in anchor elements do have `alt` attribute added:

![anchorWithAlt](https://github.com/mdn/dom-examples/assets/157268750/53d3edbc-db99-4572-8bbe-c747739a5831)

### What did you expect to see?

In the [script.js](https://github.com/mdn/dom-examples/blob/main/view-transitions/spa/script.js) file, I suggest adding the following code:
```js
galleryImg.alt = imageData[0].name; // in the init() function
galleryImg.alt = targetIdentifier.alt; // in the displayNewImage() method inside updateView() function
```

### Do you have any supporting links, references, or citations?

*"If there is even the slightest possibility of the author having the ability to provide real alternative text, then it would not be acceptable to omit the [alt](https://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#attr-img-alt) attribute."* - [W3's documentation](https://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#figcaption-as-alt-condition)

### Do you have anything more you want to share?

Upon reviewer's approval, I'll create a PR to fix this issue.

**Comment by bsmth** [comment]
Thanks a lot for opening, I think you can go ahead and create a PR for this 👍🏻
