### ISSUE TITLE
Small grammar error on MediaDevicesInfo page

### ISSUE THREAD

**Issue by AncyentMariner** [mdn/dom-examples#4]
This is a definite nitpick, but I noticed it when I was on this page -- https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo

There is a grammar error in the sentence : "Two devices have the same group identifier if they belong to the same physical device; for example a monitor with both a built-in camera and microphone."

After the semicolon, the is a sentence fragment. To fix this, you could make this semicolon a comma (or emdash, if you're feeling fancy!). 

Hopefully this is helpful.
Thanks! 
-jeff

**Comment by chrisdavidmills** [comment]
Yup, I agree with that. Updated! Thanks for pointing it out.
