### ISSUE TITLE
chroma key green screen video pre-requisites

### ISSUE THREAD

**Issue by inglesuniversal** [mdn/dom-examples#52]
I tried adding a video of my own with green background and it does not turn transparent.

Do I need to follow certain guidelines?

Regards

**Comment by chrisdavidmills** [comment]
I have checked it, and the orginal version words in Chrome/Firefox. You do need to run it through a web server - file:// URLs won't work.

**Comment by TheWizardofWikacy** [comment]
Do you mean it has to be a file on the same server as the script, or that the file has to be on any server?  I tried it with image and video o cloudinary public server and it didn't work.  Also, is there an sdk or library I need to import?

**Comment by inglesuniversal** [comment]
In other words, I think the issue has to do with the green color I applied to the source video which is equivalent to "lime" web color #00FF00 .... Do I have to generate my videos with a specific hex color for the chroma key effect to work?

**Comment by caugner** [comment]
It looks like the question is related to the [chroma-keyring example](https://github.com/mdn/dom-examples/tree/main/canvas/chroma-keying).
