### ISSUE TITLE
Error not handled properly in offline video player example fetch call?

### ISSUE THREAD

**Issue by darpankumar** [mdn/dom-examples#53]
In this demo, the error is not handled properly whenever there is an error in the fetch call i.e 404 video is not available then also it says video ready to play PFA the screenshot in which the api return 404 but it says the video is ready to play. I know it is the default behaviour of fetch API it calls reject only if the service is not available but we need to handle this scenario in our code.
URl for the demo file 
https://github.com/mdn/dom-examples/blob/master/abort-api/index.html

<img width="1668" alt="Screenshot 2020-03-07 at 3 26 37 PM" src="https://user-images.githubusercontent.com/21257218/76141285-bebb8300-6088-11ea-95d1-2c5bc78fafe8.png">

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #2916](https://github.com/mdn/sprints/issues/2916) via [**ZenHub**](https://www.zenhub.com/)
