### ISSUE TITLE
performance-apis - Using_the_Resource_Timing_API.html

### ISSUE THREAD

**Issue by earthlng** [mdn/dom-examples#7]
https://github.com/mdn/dom-examples/blob/master/performance-apis/Using_the_Resource_Timing_API.html#L139

```js
// Secure connection time
t = (resources[i].secureConnectionStart > 0) ? "0" : (resources[i].connectEnd - resources[i].secureConnectionStart);
```

shouldn't the if-else be the other way around?
```js
t = (resources[i].secureConnectionStart > 0) ? (resources[i].connectEnd - resources[i].secureConnectionStart) : "0";
```

the last 3 `t` definitions in that function also need fixing.

**Comment by chrisdavidmills** [comment]
Yup, you are right. In the related article on MDN, they are the other way round too ;-)

I've fixed it. Thanks for reporting.
