### ISSUE TITLE
Can't make dom-examples/screen-wake-lock-api work

### ISSUE THREAD

**Issue by LuckCky** [mdn/dom-examples#83]
Hi!
Thanks for providing this example.
https://github.com/mdn/dom-examples/tree/master/screen-wake-lock-api

## Expected Behavior
Button 'turn wake lock on' is active.
Text in the box 'wake lock status' is 'Screen Wake Lock API supported 🎉'

## Current Behavior
Button 'turn wake lock on' is inactive.
Text in the box 'wake lock status' is 'Wake lock is not supported by this browser.'

## Possible Solution
Unknown to me

## Steps to Reproduce
1. Debian 9 server
2. nginx/1.10.3
3. add three files from repo to /var/www/html
4. set up Nginx to serve index.html
5. Chrome Version 91.0.4472.114 (Official Build) (x86_64)
6. No https (might it be an issue?)

No errors shown, just button is inactive.
How can I make it work as it's working in your demo (https://mdn.github.io/dom-examples/screen-wake-lock-api/)?

**Comment by tomayac** [comment]
Bullet 6. is the problem indeed. The HTTP**S** requirement is mentioned in the [article](https://web.dev/wake-lock/#:~:text=like%20most%20other%20powerful%20web%20apis%2C%20the%20screen%20wake%20lock%20api%20is%20only%20available%20when%20served%20over%20https.) and the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/WakeLock#:~:text=secure%20context). I just tried the demo on Chrome 91 and it worked.

**Comment by LuckCky** [comment]
Thanks, Thomas, that's my bad, I've missed this in the article.
